<?php

namespace Drupal\diff\Routing;

use Drupal\Core\Routing\RouteSubscriberBase;
use Symfony\Component\Routing\RouteCollection;

/**
 * Listens to the dynamic route events.
 */
class RouteSubscriber extends RouteSubscriberBase {

  /**
   * {@inheritdoc}
   */
  public function alterRoutes(RouteCollection $collection) {
    // Replace the content from node.revision_overview route with content
    // generated by revisionOverview method from NodeRevisionController class.
    $route = $collection->get('entity.node.version_history');
    if ($route) {
      $route->addDefaults(
        array(
          '_controller' => '\Drupal\diff\Controller\NodeRevisionController::revisionOverview',
        )
      );
    }

    $entity_types = \Drupal::entityTypeManager()->getDefinitions();
    foreach ($entity_types as $entity_type) {
      // Node already handled.
      if ($entity_type->id() == 'node') {
        continue;
      }
      if (!$entity_type->hasLinkTemplate('revisions-diff') || !$entity_type->hasHandlerClass('route_provider', 'html_diff')) {
        continue;
      }

      $route = $collection->get("entity.{$entity_type->id()}.version_history");
      if ($route) {
        $route->addDefaults(
          array(
            '_controller' => '\Drupal\diff\Controller\EntityRevisionController::revisionOverview',
            '_entity_revisions_overview' => $entity_type->id(),
          )
        );
      }
    }
  }

}
